name: Hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hi"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: goodbye world
        run: echo "goodbye world"
        shell: bash
    
  bye:
    runs-on: ubuntu-latest
    steps:
      - name: bye world
        run: echo "bye world"
        shell: bash
        
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: hi world
        run: echo "hi world"
        shell: bash
        
        
  by:
    runs-on: ubuntu-latest
    needs: [goodbye, bye]
    steps:
      - name: by world
        run: echo "by world"
        shell: bash
        
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test world
        run: echo "test world"
        shell: bash
        
