name: simran world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: hi simran world
        run: echo "hello world"
        shell: bash

  bye:
    runs-on: ubuntu-latest
    steps:
      - name: bye simran world
        run: echo "goodbye world"
        shell: bash
        
